---
title: "Beach casts - Methods"
author: "Carlin Landsberg"
date: "7/3/2018"
output: 
  pdf_document: 
    latex_engine: xelatex
monofont: PT Mono
mainfont: Arial
fontsize: 11pt  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Method and materials
This study was conducted at Muizenberg Beach (3406′24.2′′S 1828′29.3′′E) in an area where kelp wrack is not cleared by the City of Cape Town (CoCT) beach cleaning teams. This site has no adjacent kelps beds to the beach but the area experiences large amounts of beach-cast kelp  on a regular basis.

Along the beach, a 10 m wide section was measured using a 10 m long rope held perpendicular to the edge of the low tide line. Two people, each holding one end of the rope, then proceeded to walk along the transect of ~250 m across the beach parallel to the low tide line.

**insert figure 1**

Along this transect, every kelp that was found within 10 m from the low tide edge was counted and various morphological charateristics were measured and recorded. These morphological characteristics included holdfast presence or absence, diameter of holdfast, stipe length, and longest frond length. Additionally, each kelp was numbered and if more than one individual was present, on the same holdfast, it was recorded with an associated number. For example, if three individuals share a holdfast, it was recorded as 1.1, 1.2, and 1.3 These clusters of individuals will hereafter be referred to as aggregates.  Stipe and frond length were measured and recorded for each kelp individual in the aggregate, provided the stipe length was at least 10cm long.

Since wave climate may vary seasonally,his method was repeated weekly from 24 March, which is late summer, throughout the winter until August/ September. This allowed temporal comparison of  morphological characteristics amongst beach-cast kelp over a varying wave climate. The SWAN (simulating waves nearshore) model was chosen to simulate wave parameters for the study site. 

##**Statistical analysis**
##*Wave climate* 
We described the measured kelp variables as a function of the various wave parameters (i.e. direction, frequency, intensity, significant height) using a redundancy analysis in order to determine which wave parameters are the biggest factors in the mode of kelp mortality and how the kelp washes up in this specific area.

##*Kelp morphology*
Additionally, we related the morphometric properties of the beach-cast kelp that we have observed to that of kelp previously collected in situ off the east side of the peninsula using a visual representation. 

Furthermore, we used a 3-D hydrodynamic numerical model to simulate releasing of particles from various kelp beds along the coast to determine the probability that individuals from a population will be distributed onto the Muizenberg beach. 


